# fly.toml app configuration file generated for hanasu on 2023-08-27T15:50:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hanasu"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
