/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IPhChatsTeardropDuotone: typeof import('~icons/ph/chats-teardrop-duotone')['default']
    IPhChatTeardropDotsDuotone: typeof import('~icons/ph/chat-teardrop-dots-duotone')['default']
    IPhChatTeardropDuotone: typeof import('~icons/ph/chat-teardrop-duotone')['default']
    IPhCheckCircleDuotone: typeof import('~icons/ph/check-circle-duotone')['default']
    IPhIdentificationCardDuotone: typeof import('~icons/ph/identification-card-duotone')['default']
    IPhIdentificationCardThin: typeof import('~icons/ph/identification-card-thin')['default']
    IPhMicrophoneStageDuotone: typeof import('~icons/ph/microphone-stage-duotone')['default']
    IPhShareNetworkDuotone: typeof import('~icons/ph/share-network-duotone')['default']
    IPhSkullDuotone: typeof import('~icons/ph/skull-duotone')['default']
    IPhSmileySadDuotone: typeof import('~icons/ph/smiley-sad-duotone')['default']
    IPhSpeakerHifiDuotone: typeof import('~icons/ph/speaker-hifi-duotone')['default']
    IPhSpiralDuotone: typeof import('~icons/ph/spiral-duotone')['default']
    IPhUserCircleGearDuotone: typeof import('~icons/ph/user-circle-gear-duotone')['default']
    IPhXCircleDuotone: typeof import('~icons/ph/x-circle-duotone')['default']
  }
}
