/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IPhChatsTeardropDuotone: typeof import('~icons/ph/chats-teardrop-duotone')['default']
    IPhChatTeardropDotsDuotone: typeof import('~icons/ph/chat-teardrop-dots-duotone')['default']
    IPhChatTeardropDuotone: typeof import('~icons/ph/chat-teardrop-duotone')['default']
    IPhSkullDuotone: typeof import('~icons/ph/skull-duotone')['default']
  }
}
