FROM node:18.17.1-alpine as pnpm
ENV PNPM_VERSION 8.6.12
RUN apk --no-cache add curl
RUN curl -sL https://unpkg.com/@pnpm/self-installer | node

FROM pnpm as install
ENV NPM_CONFIG_LOGLEVEL error
WORKDIR /usr/src/app
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY api/package.json ./api/package.json
COPY *.json ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run api start
EXPOSE 4444


CMD ["npm", "run", "start:api"]